# Generated by Django 3.0.5 on 2020-04-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200409_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='language',
            new_name='course',
        ),
    ]
