# Generated by Django 3.0.5 on 2020-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20200409_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('certificate_photo', models.ImageField(upload_to='')),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
