# Generated by Django 3.0.5 on 2020-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsAndTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_and_tech', models.CharField(max_length=50)),
            ],
        ),
    ]
